In [28]:
import numpy as np 

In [2]:
lst = [1,2,3,4,5,6,7,8,9,10]
arr = np.array([1,2,3,4,5,6,7,8,9,10])
# arr = np.array(lst)

In [3]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
lst[1]

2

In [6]:
arr[2] + lst[1]

np.int64(5)

In [7]:
lst1 = [1,2,3]
lst2 = [4,5,6]
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [29]:
[1,2,3] + [4,5,6,7]

[1, 2, 3, 4, 5, 6, 7]

In [30]:
np.array([1,2,3]) + np.array([4,5,6,7])

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [8]:
lst1 + lst2

[1, 2, 3, 4, 5, 6]

In [9]:
arr1 + arr2

array([5, 7, 9])

In [10]:
len(lst1)

3

In [11]:
len(arr1)

3

In [36]:
list_mat = [
    [1,2,3,4,5],
    [4,5,6,5,5],
    [7,8,9,6,9],
    [10,11,12,7,10]
]

len(list_mat),len(list_mat[0])
list_mat

[[1, 2, 3, 4, 5], [4, 5, 6, 5, 5], [7, 8, 9, 6, 9], [10, 11, 12, 7, 10]]

In [35]:
np.array(list_mat)

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  5,  5],
       [ 7,  8,  9,  6,  9],
       [10, 11, 12,  7, 10]])

In [13]:
list_mat

[[1, 2, 3, 4], [4, 5, 6, 5], [7, 8, 9, 6], [10, 11, 12, 7]]

In [38]:
matrix_array = np.array([[1,2,3,4],[4,5,6,5],[7,8,9,6],[10,11,12,7],[1,2,3,4]])
matrix_array

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  5],
       [ 7,  8,  9,  6],
       [10, 11, 12,  7],
       [ 1,  2,  3,  4]])

In [39]:
matrix_array.shape

(5, 4)

In [16]:
# three_d_tensor = np.array()
scalar = np.array(5) # 0d tensor
vector = np.array([1,2,3]) # 1d tensor
matrix = np.array([[1,2],[3,4],[5,6]]) # 2d tensor

In [17]:
print(f'Scalar dimensions: {scalar.ndim}')
print(f'Vector dimensions: {vector.ndim}')
print(f'Matrix dimensions: {matrix.ndim}')

Scalar dimensions: 0
Vector dimensions: 1
Matrix dimensions: 2


In [18]:
vector.ndim

1

In [19]:
matrix.ndim

2

In [43]:
threed_tensor = np.array([
    [[1,2,3],
      [4,5,6],
      [4,5,6]],
    
    [[11,12,13],
     [14,15,16],
    [4,5,6], ],
    
    # [[21,22,23],
    #   [24,25,26]],
])
# (2,2,3)
threed_tensor.shape

(2, 3, 3)

In [ ]:
lst = [[1,"how", True, 3.14], 'Hello', 1]

In [21]:
threed_tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [22]:
threed_tensor.ndim

3

In [44]:
# Data types
np.int64

numpy.int64

In [50]:
np.uint8(129)
# int - int8, int16, int32, int64, uint8, uint16, uint32, uint64
#  0000 0000
#  1111 1111
# 1 0000 0000

2**64

18446744073709551616

In [62]:
# -128 -> 127
# 0 -> 255

In [63]:
bin(256)

'0b100000000'

In [64]:
np.uint8(255)

np.uint8(255)

In [133]:
int('11111111',2)
# 1 0 0
# 4  2  1
128 + 64 + 32 + 16 + 8 + 4 + 2 + 1
0b11111111

255

In [66]:
2 ** 64

18446744073709551616

In [67]:
# np.float16 -> np.float128

In [68]:
np.float64(2.1)

np.float64(2.1)

In [72]:
np.uint8(256)

OverflowError: Python integer 256 out of bounds for uint8

In [135]:
arr = np.array([1,2,3,4.5, 127], dtype=np.int8)

In [136]:
arr.dtype

dtype('int8')

In [86]:
arr

array([1, 2, 3, 4], dtype=int8)

In [95]:
arr = np.array([1, "Hello"])
arr + arr

array(['11', 'HelloHello'], dtype='<U42')

In [101]:
int('42')

42

In [103]:
mat = np.array([[1,2], [3,4], [5,6]])
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
"""
       0  1
0 -> [ 1, 2 ]
1 -> [ 3, 4 ]
2 -> [ 5, 6 ]

"""

In [109]:
mat[1,0]

np.int64(3)

In [105]:
mat.shape

(3, 2)

In [108]:
mat[0,0]

np.int64(1)

In [110]:
threed_tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16],
        [ 4,  5,  6]]])

In [116]:
threed_tensor = np.array([
    [ # 0
     
        # 0  1  2
        [ 1, 2, 3],    #0
        [ 4, 5, 6],    #1
        [ 24,25,26]  #2
      ],
    
    [ # 1
     
        #0  1  2
        [11,12,13], #0
        [14,15,16], #1
        [34,35,36]  #2
    ],
    
    # [[21,22,23],
    #   [24,25,26]],
])
# (2,3,3)
threed_tensor.shape

(2, 3, 3)

In [128]:
threed_tensor[1, : , 2:]

array([[13],
       [16],
       [36]])

In [117]:
threed_tensor[0, 1, 2]

np.int64(6)

In [111]:
threed_tensor.ndim

3